img = [
    {
        "ID": "0",
        "country": "non",
        "img_name": "undefined",
        "path": "images/",
        "description": "undefined",
    }, {
        "ID": "1",
        "country": "Albania",
        "img_name": "Albanien.png",
        "path": "images/",
        "description": "Typisch für Albanien ist die traditionelle Tracht, die aus einem langen Hemd und einem kleinen Filzmantel, der Xhoka besteht. Oft wird zusätzlich ein auffälliger Hut, auch Qeleshe genannt, getragen.",
    }, {
        "ID": "2",
        "country": "Liechtenstein",
        "img_name": "Liechtenstein.png",
        "path": "images/",
        "description": "Bekannt ist Lichtenstein vor allem für seine Blumenkränze als Teil der traditionellen Tracht. Auf Festen werden sogar die Tiere mit Kränzen behangen.",
    }, {
        "ID": "3",
        "country": "Monaco",
        "img_name": "Monaco.png",
        "path": "images/",
        "description": "Die traditionelle Kleidung Monacos ist recht unauffällige Kleidung, die jedoch durch die Schwarzen Streifen am unteren Teil des Rockes gut wiederzuerkennen waren. Darüber wird meist eine schwarze Schürze getragen",
    }, {
        "ID": "4",
        "country": "Ukrain",
        "img_name": "Ukraine.png",
        "path": "images/",
        "description": "In der Nationaltracht der Ukraine lassen sich, wie auch bei Lichtenstein, viele Blumen wiederfinden. Typische Farben für diese Gewänder sind knalliges Rot und Weiß. Auch mit bunten Bändern wurde sich gerne zusätzlich geschmückt.",
    }, {
        "ID": "5",
        "country": "Denmark",
        "img_name": "Daenemark.png",
        "path": "images/",
        "description": "Dänemark ist bekannt für die Wikingerzeit. Damals wurde vor allem wärmende Kleidung getragen, oftmals in Kombination mit Pelzen und Fellen.",
    }, {
        "ID": "6",
        "country": "Spain",
        "img_name": "Spanien.png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "7",
        "country": "UK",
        "img_name": "England.png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "8",
        "country": "",
        "img_name": ".png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "9",
        "country": "",
        "img_name": ".png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "10",
        "country": "",
        "img_name": ".png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "11",
        "country": "",
        "img_name": ".png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    }, {
        "ID": "12",
        "country": "",
        "img_name": ".png",
        "path": "images/",
        "description": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    },
    {
        "ID": "13",
        "country": "non",
        "img_name": "undefined",
        "path": "images/",
        "description": "undefined",
    },
]